version: "3.8"

services:
  enotes-database:
    image: postgres:16
    container_name: enotes-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${POSTGRES_TZ}
      PGTZ: ${POSTGRES_PGTZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # Main LocalStack gateway
    environment:
      - SERVICES=s3,lambda,apigateway,ec2
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - ${LOCAL_STACK_DATA}:/var/lib/localstack"
