version: "3.8"

services:
  enotes-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: enotes-service:latest
    container_name: enotes-service
    env_file:
      - .env
    depends_on:
      enotes-database:
        condition: service_healthy  # ← wait for postgres to be ready
      redis:
        condition: service_started
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_EMAIL_USERNAME=${SPRING_EMAIL_USERNAME}
      - SPRING_EMAIL_PASSWORD=${SPRING_EMAIL_PASSWORD}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - LOCAL_STACK_HOST=${LOCAL_STACK_HOST}
      - GEMINI_API_URL=${GEMINI_API_URL}
    ports:
      - "8080:8080"

  enotes-database:
    image: postgres:16
    container_name: enotes-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${POSTGRES_TZ}
      PGTZ: ${POSTGRES_PGTZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: enotes-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack
    ports:
      - "4566:4566"   # Main LocalStack gateway
      - "4510-4559:4510-4559"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=s3,lambda,apigateway,ec2
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - ${LOCAL_STACK_DATA}:/var/lib/localstack
    restart: unless-stopped
