server:
  port: 8080
  servlet:
    context-path: /enotes

gemini:
  api:
    key: 
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent



spring:
  application:
    name: Enotes-INDUS
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  jwt:
    secret: "BGiBX8GENIcKINk+z2A75yW5FeeGZWDNUdEODj0HHrE="


  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 600000

  mail:
    host: smtp.gmail.com
    username: dummysingh2001002@gmail.com
    password: "sxaq vzoc fvyo vjwa"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoint:
    shutdown:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - '*'
        exclude:
          - beans
          - logger
          - env



file:
  upload:
    path: "notes/"
    pathExcel: "excelstorage/"

email:
  send:
    from: dummysingh2001002@gmail.com






---


spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/enotes
    username: root
    password: "2106@2308Ud"
#    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

---


spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    username: root
    password: "2106@2308Ud"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    username: root
    password: "2106@2308Ud"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

---



spring:
  config:
    activate:
      on-profile: uat

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    username: root
    password: "2106@2308Ud"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true


