#spring.application.name=Enotes-INDUS
#server.servlet.context-path=/enotes
#
#
## Database connection
#spring.datasource.url=jdbc:mysql://localhost:3306/enotes
#spring.datasource.username=root
#spring.datasource.password=2106@2308Ud
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
##Jpa configs
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
## ensures restart is active
#spring.devtools.restart.enabled=true
## ensures browser refresh works
#spring.devtools.livereload.enabled=true
#
#
#file.upload.path=notes/
#file.upload.pathExcel=excelstorage/
#
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
#email.send.from=dummysingh2001002@gmail.com
#spring.mail.host=smtp.gmail.com
#spring.mail.username=dummysingh2001002@gmail.com
#spring.mail.password=sxaq vzoc fvyo vjwa
#spring.mail.port=587
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.profiles.active=test